name: adventofcode_2024
description: An attempt at every solution to the Advent of Code 2024
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
